controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  - name: fake_hand_controller
    joints:
      - finger1
      - finger2
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: hand
    pose: open